// <auto-generated />
using System;
using DeLozerkermisVrienden.Organizer.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DeLozerkermisVrienden.Organizer.API.Migrations
{
    [DbContext(typeof(OrganizerContext))]
    [Migration("20200408180016_V2.1_ChangeTestData")]
    partial class V21_ChangeTestData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DeLozerkermisVrienden.Organizer.API.Entities.Betaalmethode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AantalDagenVroegerAfsluiten")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Opmerking")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int>("Volgorde")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Betaalmethoden");

                    b.HasData(
                        new
                        {
                            Id = new Guid("574fa379-3144-49c0-b1f1-5e1514e270af"),
                            Naam = "Contant",
                            Opmerking = "U betaalt bij het inchecken op de dag van het evenement zelf OF U betaalt ervoor aan een lid van de vereniging.",
                            Volgorde = 1
                        },
                        new
                        {
                            Id = new Guid("a833e881-dbdb-4a09-a718-a44d1f3ce0ea"),
                            AantalDagenVroegerAfsluiten = 5,
                            Naam = "Overschrijving",
                            Volgorde = 2
                        });
                });

            modelBuilder.Entity("DeLozerkermisVrienden.Organizer.API.Entities.Betaaltransactie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Bedrag")
                        .HasColumnType("decimal(7,2)");

                    b.Property<Guid?>("BetaalmethodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumBetaling")
                        .HasColumnType("datetime2");

                    b.Property<string>("GestructureerdeMededeling")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<Guid>("InschrijvingsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LidId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VerantwoordelijkeBetaling")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.HasIndex("BetaalmethodeId");

                    b.HasIndex("InschrijvingsId");

                    b.HasIndex("LidId");

                    b.ToTable("Betaaltransacties");
                });

            modelBuilder.Entity("DeLozerkermisVrienden.Organizer.API.Entities.CheckIn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InschrijvingsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LidId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InschrijvingsId");

                    b.HasIndex("LidId");

                    b.ToTable("CheckIns");
                });

            modelBuilder.Entity("DeLozerkermisVrienden.Organizer.API.Entities.Evenement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumEindeEvenement")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumEindeInschrijvingen")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumStartEvenement")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumStartInschrijvingen")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EvenementCategorieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.HasIndex("EvenementCategorieId");

                    b.ToTable("Evenementen");
                });

            modelBuilder.Entity("DeLozerkermisVrienden.Organizer.API.Entities.EvenementCategorie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("EvenementCategorieen");
                });

            modelBuilder.Entity("DeLozerkermisVrienden.Organizer.API.Entities.Inschrijving", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AantalAanhangwagens")
                        .HasColumnType("int");

                    b.Property<int>("AantalMeter")
                        .HasColumnType("int");

                    b.Property<int?>("AantalMobilhomes")
                        .HasColumnType("int");

                    b.Property<int?>("AantalWagens")
                        .HasColumnType("int");

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<Guid?>("BetaalmethodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumInschrijving")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<Guid>("EvenementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Gemeente")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("GestructureerdeMededeling")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<Guid?>("InschrijvingsstatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LidId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Meterprijs")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("MobielNummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(9)")
                        .HasMaxLength(9);

                    b.Property<string>("Opmerking")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(4)")
                        .HasMaxLength(4);

                    b.Property<string>("PrefixMobielNummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(6)")
                        .HasMaxLength(6);

                    b.Property<string>("QRCode")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("RedenAfkeuring")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Standnummer")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.HasIndex("BetaalmethodeId");

                    b.HasIndex("EvenementId");

                    b.HasIndex("InschrijvingsstatusId");

                    b.HasIndex("LidId");

                    b.ToTable("Inschrijvingen");
                });

            modelBuilder.Entity("DeLozerkermisVrienden.Organizer.API.Entities.Inschrijvingsstatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int>("Volgorde")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Inschrijvingsstatussen");
                });

            modelBuilder.Entity("DeLozerkermisVrienden.Organizer.API.Entities.Lid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<bool>("Actief")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("Leden");
                });

            modelBuilder.Entity("DeLozerkermisVrienden.Organizer.API.Entities.Login", b =>
                {
                    b.Property<Guid>("LidId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Wachtwoord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LidId");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("DeLozerkermisVrienden.Organizer.API.Entities.Nieuwsbrief", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<Guid>("EvenementId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EvenementId");

                    b.ToTable("Nieuwsbrieven");
                });

            modelBuilder.Entity("DeLozerkermisVrienden.Organizer.API.Entities.Betaaltransactie", b =>
                {
                    b.HasOne("DeLozerkermisVrienden.Organizer.API.Entities.Betaalmethode", "Betaalmethode")
                        .WithMany("Betaaltransacties")
                        .HasForeignKey("BetaalmethodeId");

                    b.HasOne("DeLozerkermisVrienden.Organizer.API.Entities.Inschrijving", "Inschrijving")
                        .WithMany("Betaaltransacties")
                        .HasForeignKey("InschrijvingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeLozerkermisVrienden.Organizer.API.Entities.Lid", "Lid")
                        .WithMany("Betaaltransacties")
                        .HasForeignKey("LidId");
                });

            modelBuilder.Entity("DeLozerkermisVrienden.Organizer.API.Entities.CheckIn", b =>
                {
                    b.HasOne("DeLozerkermisVrienden.Organizer.API.Entities.Inschrijving", "Inschrijving")
                        .WithMany("CheckIns")
                        .HasForeignKey("InschrijvingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeLozerkermisVrienden.Organizer.API.Entities.Lid", "Lid")
                        .WithMany("CheckIns")
                        .HasForeignKey("LidId");
                });

            modelBuilder.Entity("DeLozerkermisVrienden.Organizer.API.Entities.Evenement", b =>
                {
                    b.HasOne("DeLozerkermisVrienden.Organizer.API.Entities.EvenementCategorie", null)
                        .WithMany("Evenementen")
                        .HasForeignKey("EvenementCategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeLozerkermisVrienden.Organizer.API.Entities.Inschrijving", b =>
                {
                    b.HasOne("DeLozerkermisVrienden.Organizer.API.Entities.Betaalmethode", "Betaalmethode")
                        .WithMany("Inschrijvingen")
                        .HasForeignKey("BetaalmethodeId");

                    b.HasOne("DeLozerkermisVrienden.Organizer.API.Entities.Evenement", "Evenement")
                        .WithMany("Inschrijvingen")
                        .HasForeignKey("EvenementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeLozerkermisVrienden.Organizer.API.Entities.Inschrijvingsstatus", "Inschrijvingsstatus")
                        .WithMany("Inschrijvingen")
                        .HasForeignKey("InschrijvingsstatusId");

                    b.HasOne("DeLozerkermisVrienden.Organizer.API.Entities.Lid", "Lid")
                        .WithMany("Inschrijvingen")
                        .HasForeignKey("LidId");
                });

            modelBuilder.Entity("DeLozerkermisVrienden.Organizer.API.Entities.Login", b =>
                {
                    b.HasOne("DeLozerkermisVrienden.Organizer.API.Entities.Lid", "Lid")
                        .WithOne("Login")
                        .HasForeignKey("DeLozerkermisVrienden.Organizer.API.Entities.Login", "LidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeLozerkermisVrienden.Organizer.API.Entities.Nieuwsbrief", b =>
                {
                    b.HasOne("DeLozerkermisVrienden.Organizer.API.Entities.Evenement", "Evenement")
                        .WithMany("Nieuwsbrieven")
                        .HasForeignKey("EvenementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
